/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1kubernetesapis "github.com/GoogleCloudPlatform/gke-enterprise-mt/pkg/apis/providerconfig/v1_kubernetes_apis"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderConfigs implements ProviderConfigInterface
type FakeProviderConfigs struct {
	Fake *FakeCloudV1_kubernetes_apis
	ns   string
}

var providerconfigsResource = v1kubernetesapis.SchemeGroupVersion.WithResource("providerconfigs")

var providerconfigsKind = v1kubernetesapis.SchemeGroupVersion.WithKind("ProviderConfig")

// Get takes name of the providerConfig, and returns the corresponding providerConfig object, and an error if there is any.
func (c *FakeProviderConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1kubernetesapis.ProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(providerconfigsResource, c.ns, name), &v1kubernetesapis.ProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1kubernetesapis.ProviderConfig), err
}

// List takes label and field selectors, and returns the list of ProviderConfigs that match those selectors.
func (c *FakeProviderConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1kubernetesapis.ProviderConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(providerconfigsResource, providerconfigsKind, c.ns, opts), &v1kubernetesapis.ProviderConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1kubernetesapis.ProviderConfigList{ListMeta: obj.(*v1kubernetesapis.ProviderConfigList).ListMeta}
	for _, item := range obj.(*v1kubernetesapis.ProviderConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerConfigs.
func (c *FakeProviderConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(providerconfigsResource, c.ns, opts))

}

// Create takes the representation of a providerConfig and creates it.  Returns the server's representation of the providerConfig, and an error, if there is any.
func (c *FakeProviderConfigs) Create(ctx context.Context, providerConfig *v1kubernetesapis.ProviderConfig, opts v1.CreateOptions) (result *v1kubernetesapis.ProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(providerconfigsResource, c.ns, providerConfig), &v1kubernetesapis.ProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1kubernetesapis.ProviderConfig), err
}

// Update takes the representation of a providerConfig and updates it. Returns the server's representation of the providerConfig, and an error, if there is any.
func (c *FakeProviderConfigs) Update(ctx context.Context, providerConfig *v1kubernetesapis.ProviderConfig, opts v1.UpdateOptions) (result *v1kubernetesapis.ProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(providerconfigsResource, c.ns, providerConfig), &v1kubernetesapis.ProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1kubernetesapis.ProviderConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderConfigs) UpdateStatus(ctx context.Context, providerConfig *v1kubernetesapis.ProviderConfig, opts v1.UpdateOptions) (*v1kubernetesapis.ProviderConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(providerconfigsResource, "status", c.ns, providerConfig), &v1kubernetesapis.ProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1kubernetesapis.ProviderConfig), err
}

// Delete takes name of the providerConfig and deletes it. Returns an error if one occurs.
func (c *FakeProviderConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(providerconfigsResource, c.ns, name, opts), &v1kubernetesapis.ProviderConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(providerconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1kubernetesapis.ProviderConfigList{})
	return err
}

// Patch applies the patch and returns the patched providerConfig.
func (c *FakeProviderConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1kubernetesapis.ProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providerconfigsResource, c.ns, name, pt, data, subresources...), &v1kubernetesapis.ProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1kubernetesapis.ProviderConfig), err
}
