/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1_kubernetes_apis

import (
	"net/http"

	v1kubernetesapis "github.com/GoogleCloudPlatform/gke-enterprise-mt/pkg/apis/providerconfig/v1_kubernetes_apis"
	"github.com/GoogleCloudPlatform/gke-enterprise-mt/pkg/providerconfig/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type CloudV1_kubernetes_apisInterface interface {
	RESTClient() rest.Interface
	ProviderConfigsGetter
}

// CloudV1_kubernetes_apisClient is used to interact with features provided by the cloud.gke.io group.
type CloudV1_kubernetes_apisClient struct {
	restClient rest.Interface
}

func (c *CloudV1_kubernetes_apisClient) ProviderConfigs(namespace string) ProviderConfigInterface {
	return newProviderConfigs(c, namespace)
}

// NewForConfig creates a new CloudV1_kubernetes_apisClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*CloudV1_kubernetes_apisClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new CloudV1_kubernetes_apisClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*CloudV1_kubernetes_apisClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &CloudV1_kubernetes_apisClient{client}, nil
}

// NewForConfigOrDie creates a new CloudV1_kubernetes_apisClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CloudV1_kubernetes_apisClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CloudV1_kubernetes_apisClient for the given RESTClient.
func New(c rest.Interface) *CloudV1_kubernetes_apisClient {
	return &CloudV1_kubernetes_apisClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1kubernetesapis.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CloudV1_kubernetes_apisClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
