package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Tenant is the Schema for the Tenant resource in the MT cluster.
//
// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster
// +k8s:deepcopy-gen:interfaces=google3/third_party/kubernetes_apis/k8s_io/apimachinery/pkg/runtime/runtime.Object
type Tenant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TenantSpec   `json:"spec"`
	Status TenantStatus `json:"status,omitempty"`
}

// TenantList contains a list of Tenants.
//
// +kubebuilder:object:root=true
// +k8s:deepcopy-gen:interfaces=google3/third_party/kubernetes_apis/k8s_io/apimachinery/pkg/runtime/runtime.Object
type TenantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tenant `json:"items"`
}

// NetworkConfig defines the network configuration of the tenant.
//
// Deprecated: This type is deprecated and will be removed in a future release. Use ProviderConfig instead for network configuration.
type NetworkConfig struct {
	// The network (VPC) in the tenant project that will be used for the tenant.
	// Format is `projects/{tenantProject}/global/networks/{network}`.
	//
	// +kubebuilder:validation:Optional
	Network string `json:"network"`
	// The information of the subnet in the tenant VPC that will be used for the tenant.
	//
	// +kubebuilder:validation:Optional
	SubnetInfo SubnetInfo `json:"subnetInfo"`
}

// SubnetInfo defines the subnet information of the tenant.
type SubnetInfo struct {
	// The subnet in the tenant VPC that will be used for the tenant.
	// Format is`projects/{tenantProject}/regions/{region}/subnetworks/{subnet}`.
	//
	// +kubebuilder:validation:Optional
	Subnetwork string `json:"subnetwork"`
	// The primary IP range of the subnet in CIDR notation (e.g.,`10.0.0.0/16`).
	//
	// +kubebuilder:validation:Optional
	CIDR string `json:"cidr"`
	// The information of the tenant pod ranges.
	//
	// +kubebuilder:validation:Optional
	PodRanges []SecondaryRange `json:"podRanges"`
}

// SecondaryRange defines a secondary range of the tenant subnet.
type SecondaryRange struct {
	// The name of the secondary range.
	//
	// +kubebuilder:validation:Optional
	Name string `json:"name"`
	// The secondary IP range in CIDR notation (e.g.,`10.0.0.0/16`).
	//
	// +kubebuilder:validation:Optional
	CIDR string `json:"cidr"`
}

// TenantSpec specifies the desired state of the tenant in the MT cluster.
type TenantSpec struct {
	// GCP project number where the tenant is to be created.
	//
	// +kubebuilder:validation:Minimum=0
	// +(Validation done in accordance with go/elysium/project_ids#project-number)
	ProjectNumber int64 `json:"projectNumber"`
	// GCP project ID where the tenant is to be created.
	//
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=30
	// +(Validation done in accordance with https://cloud.google.com/resource-manager/docs/creating-managing-projects#before_you_begin)
	ProjectID string `json:"projectID"`
	// PSC connection ID of the tenant PSC endpoint.
	//
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Optional
	PSCConnectionID int64 `json:"pscConnectionID"`

	// Network configuration of the tenant.

	// +kubebuilder:validation:Optional
	// Deprecated: This field is deprecated and will be removed in a future release.
	NetworkConfig NetworkConfig `json:"networkConfig"`

	// Unique ID for the tenant generated by tenancy service.
	//
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Optional
	UID string `json:"UID"`

	// Whether to enable dataplane over GKFE.
	//
	// +kubebuilder:validation:Optional
	EnableDataplaneOverGKFE bool `json:"enableDataplaneOverGKFE,omitempty"`

	// DNS GKFE alias for the tenant.
	//
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Optional
	DNSAlias string `json:"dnsAlias,omitempty"`

	// Tenant CA stores the public certificates of the per-tenant Certificate Authority (CA).
	//
	// +kubebuilder:validation:Optional
	TenantCACerts []string `json:"tenantCACerts,omitempty"`
}

// TenantStatus stores the observed state of the tenant.
type TenantStatus struct {
	// Conditions describe the current state of the Tenant.
	//
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}
